<?php
// ============================================================
// TUTORS — dati dei tutorial, aggiungi qui per espandere
// ============================================================
$tutorials = [
    [
        'id'      => 0,
        'title'   => 'Guida JavaScript',
        'category' => 'js',
        'level'   => 'medium',
        'desc'    => 'Import script, eventi, DOM, Promise, Fetch API e quiz finale.',
        'tags'    => ['async/await', 'DOM', 'fetch'],
        'pages'   => '6 pagine',
        'file'    => 'tutorials/js-tutorial.html',
    ],
    [
        'id'      => 1,
        'title'   => 'HTML — Semantica e Struttura',
        'category' => 'html',
        'level'   => 'easy',
        'desc'    => 'Tag fondamentali, formulari, tabelle e accessibilità.',
        'tags'    => ['form', 'semantica'],
        'pages'   => 'in arrivo',
        'file'    => null,
    ],
    [
        'id'      => 2,
        'title'   => 'CSS — Flexbox e Grid',
        'category' => 'css',
        'level'   => 'medium',
        'desc'    => 'Layout moderni con Flexbox e CSS Grid, media queries e variabili.',
        'tags'    => ['flexbox', 'grid', 'responsive'],
        'pages'   => 'in arrivo',
        'file'    => null,
    ],
    [
        'id'      => 3,
        'title'   => 'Git — Version Control',
        'category' => 'git',
        'level'   => 'easy',
        'desc'    => 'Repository, commit, branch, merge e flusso di lavoro collaborativo.',
        'tags'    => ['commit', 'branch'],
        'pages'   => 'in arrivo',
        'file'    => null,
    ],
    [
        'id'      => 4,
        'title'   => 'SQL — Basi di Dati',
        'category' => 'db',
        'level'   => 'hard',
        'desc'    => 'Query SELECT, JOIN, INSERT, UPDATE e modellazione ER.',
        'tags'    => ['SQL', 'JOIN', 'ERD'],
        'pages'   => 'in arrivo',
        'file'    => null,
    ],
    [
        'id'      => 5,
        'title'   => 'HTTP e il Web',
        'category' => 'net',
        'level'   => 'medium',
        'desc'    => 'Richieste HTTP, metodi, status code, DNS e struttura URL.',
        'tags'    => ['HTTP', 'DNS', 'URL'],
        'pages'   => 'in arrivo',
        'file'    => null,
    ],
    [
        'id'      => 6,
        'title'   => 'Cisco Packet Tracer — Introduzione',
        'category' => 'networking',
        'level'   => 'easy',
        'desc'    => 'Cos\'è Packet Tracer, interfaccia, dispositivi, cavi e primo topology basics.',
        'tags'    => ['Cisco', 'topologia', 'switch', 'router'],
        'pages'   => '4 pagine',
        'file'    => 'tutorials/packet-tracer.html',
    ],
    [
        'id'      => 7,
        'title'   => 'JavaFX con Maven — IntelliJ e VSCode',
        'category' => 'java',
        'level'   => 'medium',
        'desc'    => 'Setup GNI, struttura Maven, JavaFX, run/debug e packaging essenziale.',
        'tags'    => ['JavaFX', 'Maven', 'IDE'],
        'pages'   => '7 pagine',
        'file'    => 'tutorials/javafx-maven.html',
    ],
    [
	'id'	   => 8,
        'title'    => 'Grafi e Algoritmi — Visualizzazione interattiva',
        'category' => 'algo',
        'level'    => 'medium',
        'desc'     => 'BFS, DFS, Dijkstra, Bellman-Ford, Prim, Kruskal: animazioni, tabelle di traccia e spiegazioni passo-passo.',
        'tags'     => ['BFS', 'DFS', 'Dijkstra', 'MST', 'cammini minimi'],
        'pages'    => 'interattivo',
        'file'     => 'tutorials/grafi.html',
    ],
    [
        'id'       => 9,
        'title'    => 'Verifica di Matematica — Flessi, Max/Min, Teoremi',
        'category' => 'math',
        'level'    => 'medium',
        'desc'     => 'Teoremi del calcolo differenziale (Rolle, Lagrange, Cauchy, De L\'Hôpital), flessi, problemi di massimo e minimo con grafici interattivi.',
        'tags'     => ['analisi', 'derivate', 'flessi', 'max/min'],
        'pages'    => '6 pagine',
        'file'     => 'tutorials/matematica.html',
    ],
];
